data:
    filename: data/Text_Only_Ascii_Coll_MWI_NoSem
    query: data/query/request.txt
    xml_folder: data/coll/
    run_folder: data/runs/
    caching: True
    persist_index: data/persist/data_index.pkl
    persist_length: data/persist/data_length.pkl
    group:
run_step:
    step: 1
    step_min: 15
    w_func: bm25
    search_level: k1_1.2_b_0.75_articles