data:
    filename: data/Text_Only_Ascii_Coll_MWI_NoSem
    query: data/query/request.txt
    xml_folder: data/coll/
    run_folder: data/runs/
    persist: data/persist
    caching: True

run_step:
    step: 1
    step_min: 2
    w_func: btc
    search_level: articles